<?php
/**
 * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
 */
class TelegramBot{
    const API_URL = "https://api.telegram.org/bot";
    public $token;
    public $chatId;
    public $newsApiKey = 'YOUR_API_KEY'; //http://newsapi.org
    public $weatherApiKey = 'YOUR_API_KEY'; //http://api.weatherstack.com/

    /**
     * @param string $token
     * @return void
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function setToken(string $token):void
    {
        $this->token = $token;        
    }

    /**
     * @param string $method This bot
     * @param array $posts
     * @return void
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function request(string $method,array $posts)
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        $url = self::API_URL . $this->token . '/' . $method;
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($posts));
        curl_setopt($ch, CURLOPT_POST, 1);        

        $headers = array();
        $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        $result = curl_exec($ch);

        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return $result;
    }

     /**
     * @return string
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function getNews():string
    {
        $url = json_decode(file_get_contents('http://newsapi.org/v2/top-headlines?country=tr&apiKey='.$this->newsApiKey));
        $news = $url->articles[rand(0,19)];
        $zaman = explode('T',$news->publishedAt);
        $tarih = $zaman[0];
        $saat = str_replace('Z','',$zaman[1]);
        $metin = '
        '.$news->title.'
        '.$saat.' - '.$tarih.'
        '.$news->description.'
        '.$news->url.'
        ';
        return $metin;
    }

    /** required api key
     * @param string $country 
     * @return string
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function getWeather(string $country) : string 
    {
        $url = json_decode(file_get_contents('http://api.weatherstack.com/current?access_key='.$this->weatherApiKey.'&query='.$this->slug($country)));
        if (@!($url->error)) {
            $result = $url->location->name.' ili şu an '.$url->current->temperature.' at temperature.
            '.$url->location->name . ' - ' . $url->location->country;
        }else{
            $result = 'Please do not use special characters in the city name!';
        }
        return $result;
    }

    /**
     * @param string $url YOUR_WEBHOOK_URL_ADRESS
     * @return void
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function setWebhook(string $url)
    {
        return $this->request('setWebhook',[
            'url' => $url
        ]);
    }


    public function getData()
    {
        $data = json_decode(file_get_contents('php://input'));
        $this->chatId = $data->message->chat->id;
        return $data->message; 

    }

    /**
     * @param string $message
     * @return mixed
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function sendMessage(string $message) : mixed
    {
        return $this->request('sendMessage',[
            'chat_id' => $this->chatId,
            'text' => $message
        ]);
    }
    /**
     * @param [type] $photo PHOTO_URL
     * @param string $caption PHOTO_CAPTION
     * @return mixed
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function sendPhoto(string $photo,string $caption="") : mixed
    {
        return $this->request('sendPhoto',[
            'chat_id' => $this->chatId,
            'photo' => $photo,
            'caption' => $caption
        ]);
    }
    /**
     * @param string $text text to slug text
     * @return string
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public static function slug(string $text) : string 
    {
        $text = preg_replace('~[^\pL\d]+~u', '-', $text);
        $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
        $text = preg_replace('~[^-\w]+~', '', $text);
        $text = trim($text, '-');
        $text = preg_replace('~-+~', '-', $text);
        $text = strtolower($text);
        if (empty($text)) {
            return 'n-a';
        }
        return $text;
    }
    /**
     * @return string
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function getFood() : string
    {
        $foods = ['burger','pizza'];
        $food = $foods[rand(0,1)];
        $url = 'https://foodish-api.herokuapp.com/images/'.$food.'/'.$food.''.rand(1,77).'.jpg';
        return $url;
    }

    /**
     * required api key => https://api.thecatapi.com
     * @return mixed
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function getCat() : mixed
    {
        $cats = json_decode(file_get_contents('https://api.thecatapi.com/v1/images/search?limit=100&page='.rand(1,96).'&order=Desc&api_key=YOUR_API_KEY')); 
        $cat = $cats[rand(0,99)];
        if (isset($cat->breeds[0])) {
            $caption = $cat->breeds[0]->name;
            $url = $cat->url;
        }else{           
            $caption = '';
            $url = $cat->url;
        }
        return [$url,$caption];
    }

    /**
     * https://dog.ceo/api/breeds/image/random RANDOM DOG IMAGE
     * @return string
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function getDog() : string 
    {
        $url = json_decode(file_get_contents('https://dog.ceo/api/breeds/image/random'));
        if ($url->status == 'success') {
            return $url->message;
        }
    }

    /**
     * @return mixed
     * @author Ömer Faruk GÖL <omerfarukgol@hotmail.com>
     */
    public function getRandomPhoto() : mixed
    {
        $url = json_decode(file_get_contents('https://picsum.photos/v2/list?page='.rand(0,10).'&limit=100'));
        $data = $url[rand(0,92)];
        return $data;
    }
}

